version: "3.7"
services:
    redis:
        hostname: redis
        image: redislabs/redismod:latest
        volumes:
          - ${PWD-.}/redis:/data
        restart: unless-stopped
                
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: unless-stopped
        links:
            - "redis:redis"
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"

    swlor-server:
        hostname: nwnx-server
        stop_signal: SIGINT
        image: swlor/server:8193.35.40
        env_file: ${PWD-.}/swlor.env
        links:
            - "redis:redis"
        stdin_open: true
        tty: true
        volumes:
            - ${PWD-.}/logs:/nwn/run/logs.0
            - ${PWD-.}/:/nwn/home
            - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
        ports:
            - "5121:5121/udp"
            
    influxdb:
        hostname: influxdb
        image: influxdb:1.8
        restart: unless-stopped
        environment:
            - INFLUXDB_DB=nwn
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
            - INFLUXDB_USER=docker
            - INFLUXDB_USER_PASSWORD=docker
            - INFLUXDB_UDP_ENABLED=true
            - INFLUXDB_UDP_BIND_ADDRESS=:8089
            - INFLUXDB_UDP_DATABASE=nwn
        volumes:
            - ./influxdb:/var/lib/influxdb
        ports:
            - "8086"
            - "8089"
            
    grafana:
        hostname: grafana
        image: grafana/grafana:latest
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - influxdb
        volumes:
            - ./grafana-provisioning:/etc/grafana/provisioning
            - grafana:/var/lib/grafana
        ports:
            - "3000:3000"
            
volumes:
    influxdb:
    grafana: