version: "3.7"

services:
    mssql:
        hostname: mssql
        image: microsoft/mssql-server-linux:2017-latest
        environment:
            - SA_PASSWORD=StRoNgP@sSwOrD!
            - ACCEPT_EULA=Y
        ports: 
            - "5434:1433"
        networks:
          swlor_network:
            ipv4_address: 172.22.0.100
        volumes:
            - ./mssql:/var/opt/mssql

    swlor-server:
        hostname: nwnx-server
        image: nwnxee/unified:latest
        env_file: ${PWD-.}/swlor.env
        stdin_open: true
        tty: true
        depends_on:
            - mssql
        volumes:
            - ${PWD-.}/logs:/nwn/run/logs.0
            - ${PWD-.}/:/nwn/home
            - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
            - ${PWD-.}/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
        ports:
            - "5121:5121/udp"
        networks:
          swlor_network:
            ipv4_address: 172.22.0.101
            
networks:
    swlor_network:
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/16